# Generated by Django 3.2.9 on 2021-11-28 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottieAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(default=None, null=True, upload_to='wagtail_lottie/tmp', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='ZIP file')),
                ('play_mode', models.CharField(choices=[('play_auto', 'Start playing as soon as it is ready'), ('play_intersection', 'Start playing at intersection'), ('play_manual', 'Start playing when play() is called')], default='play_auto', max_length=20)),
                ('loop', models.BooleanField(default=True)),
                ('renderer', models.CharField(choices=[('svg', 'Svg'), ('canvas', 'Canvas'), ('html', 'Html')], default='svg', max_length=20)),
                ('prefers_color_scheme', models.CharField(choices=[('no_scheme', 'No preference'), ('scheme_light', 'Light'), ('scheme_dark', 'Dark')], default='no_scheme', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('uuid', models.CharField(default=None, max_length=32, null=True)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('version', models.CharField(default=None, max_length=20, null=True)),
                ('width', models.PositiveIntegerField(default=None, null=True)),
                ('height', models.PositiveIntegerField(default=None, null=True)),
                ('json_file', models.FileField(default=None, null=True, upload_to='wagtail_lottie', verbose_name='Json file')),
            ],
        ),
        migrations.CreateModel(
            name='LottieAnimationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='wagtail_lottie', verbose_name='Image file')),
                ('animation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtail_lottie.lottieanimation')),
            ],
        ),
    ]
