# Generated by Django 3.2.9 on 2021-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_lottie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lottieanimation',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='lottieanimation',
            name='preserve_aspect_ratio',
            field=models.CharField(choices=[('xMidYMid meet', 'xMidYMid meet'), ('none', 'None'), ('xMinYMin meet', 'xMinYMin meet'), ('xMidYMin meet', 'xMidYMin meet'), ('xMaxYMin meet', 'xMaxYMin meet'), ('xMinYMid meet', 'xMinYMid meet'), ('xMaxYMid meet', 'xMaxYMid meet'), ('xMinYMax meet', 'xMinYMax meet'), ('xMidYMax meet', 'xMidYMax meet'), ('xMaxYMax meet', 'xMaxYMax meet'), ('xMinYMin slice', 'xMinYMin slice'), ('xMidYMin slice', 'xMidYMin slice'), ('xMaxYMin slice', 'xMaxYMin slice'), ('xMinYMid slice', 'xMinYMid slice'), ('xMidYMid slice', 'xMidYMid slice'), ('xMaxYMid slice', 'xMaxYMid slice'), ('xMinYMax slice', 'xMinYMax slice'), ('xMidYMax slice', 'xMidYMax slice'), ('xMaxYMax slice', 'xMaxYMax slice')], default='xMidYMid meet', max_length=20),
        ),
    ]
