# Generated by Django 3.2.9 on 2021-12-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_lottie', '0002_auto_20211202_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottieanimation',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
