# Generated by Django 3.2.9 on 2021-11-28 16:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_lottie.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_lottie', '0001_initial'),
        ('app', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lottie_animation_foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_lottie.lottieanimation'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='lottie_animation_stream_field',
            field=wagtail.core.fields.StreamField([('lottie_animation_block', wagtail_lottie.blocks.LottieAnimationChooserBlock()), ('rich_text', wagtail.core.blocks.RichTextBlock())], blank=True, default=None),
        ),
    ]
